server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datax?characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true
    username: root
    password: 123456
    tomcat:
      init-s-q-l: SET NAMES utf8mb4
  jpa:
    hibernate:

      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # 下划线才行
        show_sql: false
        generate_statistics: false      #打印执行时间统计信息




  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/webGUI/
    mode: HTML5
    encoding: UTF-8

#  ├─src
#  │  │  main.py
#  │  │  res.jpg
#  │  │
#  │  ├─algorithm
#  │  │      prediction.py
#  │  │      resnet50_coco_best_v2.1.0.h5
#  │  │
#  │  ├─tkinter
#  │  │      APP.py
#  │  │
#  │  └─utils
#  │          camera.py
#  │          hardware_utils.py
#  │          junk_category_utils.py
#  │          tkinter_utils.py